/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppAgentsIndexRouteImport } from './routes/app/agents.index'
import { Route as AppAudiencesIndexRouteImport } from './routes/app/audiences.index'
import { Route as AppBillingIndexRouteImport } from './routes/app/billing.index'
import { Route as AppIntegrationsIndexRouteImport } from './routes/app/integrations.index'
import { Route as AppSettingsIndexRouteImport } from './routes/app/settings.index'
import { Route as AppSignalsIndexRouteImport } from './routes/app/signals.index'
import { Route as AppTablesIndexRouteImport } from './routes/app/tables.index'
import { Route as AppTablesTableIdRouteImport } from './routes/app/tables.$tableId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAgentsIndexRoute = AppAgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAudiencesIndexRoute = AppAudiencesIndexRouteImport.update({
  id: '/audiences/',
  path: '/audiences/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppBillingIndexRoute = AppBillingIndexRouteImport.update({
  id: '/billing/',
  path: '/billing/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppIntegrationsIndexRoute = AppIntegrationsIndexRouteImport.update({
  id: '/integrations/',
  path: '/integrations/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSignalsIndexRoute = AppSignalsIndexRouteImport.update({
  id: '/signals/',
  path: '/signals/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTablesIndexRoute = AppTablesIndexRouteImport.update({
  id: '/tables/',
  path: '/tables/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTablesTableIdRoute = AppTablesTableIdRouteImport.update({
  id: '/tables/$tableId',
  path: '/tables/$tableId',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/tables/$tableId': typeof AppTablesTableIdRoute
  '/app/agents/': typeof AppAgentsIndexRoute
  '/app/audiences/': typeof AppAudiencesIndexRoute
  '/app/billing/': typeof AppBillingIndexRoute
  '/app/integrations/': typeof AppIntegrationsIndexRoute
  '/app/settings/': typeof AppSettingsIndexRoute
  '/app/signals/': typeof AppSignalsIndexRoute
  '/app/tables/': typeof AppTablesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/tables/$tableId': typeof AppTablesTableIdRoute
  '/app/agents': typeof AppAgentsIndexRoute
  '/app/audiences': typeof AppAudiencesIndexRoute
  '/app/billing': typeof AppBillingIndexRoute
  '/app/integrations': typeof AppIntegrationsIndexRoute
  '/app/settings': typeof AppSettingsIndexRoute
  '/app/signals': typeof AppSignalsIndexRoute
  '/app/tables': typeof AppTablesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/tables/$tableId': typeof AppTablesTableIdRoute
  '/app/agents/': typeof AppAgentsIndexRoute
  '/app/audiences/': typeof AppAudiencesIndexRoute
  '/app/billing/': typeof AppBillingIndexRoute
  '/app/integrations/': typeof AppIntegrationsIndexRoute
  '/app/settings/': typeof AppSettingsIndexRoute
  '/app/signals/': typeof AppSignalsIndexRoute
  '/app/tables/': typeof AppTablesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/app/'
    | '/api/auth/$'
    | '/app/tables/$tableId'
    | '/app/agents/'
    | '/app/audiences/'
    | '/app/billing/'
    | '/app/integrations/'
    | '/app/settings/'
    | '/app/signals/'
    | '/app/tables/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/app'
    | '/api/auth/$'
    | '/app/tables/$tableId'
    | '/app/agents'
    | '/app/audiences'
    | '/app/billing'
    | '/app/integrations'
    | '/app/settings'
    | '/app/signals'
    | '/app/tables'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/app/'
    | '/api/auth/$'
    | '/app/tables/$tableId'
    | '/app/agents/'
    | '/app/audiences/'
    | '/app/billing/'
    | '/app/integrations/'
    | '/app/settings/'
    | '/app/signals/'
    | '/app/tables/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/agents/': {
      id: '/app/agents/'
      path: '/agents'
      fullPath: '/app/agents/'
      preLoaderRoute: typeof AppAgentsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/audiences/': {
      id: '/app/audiences/'
      path: '/audiences'
      fullPath: '/app/audiences/'
      preLoaderRoute: typeof AppAudiencesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/billing/': {
      id: '/app/billing/'
      path: '/billing'
      fullPath: '/app/billing/'
      preLoaderRoute: typeof AppBillingIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/integrations/': {
      id: '/app/integrations/'
      path: '/integrations'
      fullPath: '/app/integrations/'
      preLoaderRoute: typeof AppIntegrationsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/settings/': {
      id: '/app/settings/'
      path: '/settings'
      fullPath: '/app/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/signals/': {
      id: '/app/signals/'
      path: '/signals'
      fullPath: '/app/signals/'
      preLoaderRoute: typeof AppSignalsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/tables/': {
      id: '/app/tables/'
      path: '/tables'
      fullPath: '/app/tables/'
      preLoaderRoute: typeof AppTablesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/tables/$tableId': {
      id: '/app/tables/$tableId'
      path: '/tables/$tableId'
      fullPath: '/app/tables/$tableId'
      preLoaderRoute: typeof AppTablesTableIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppTablesTableIdRoute: typeof AppTablesTableIdRoute
  AppAgentsIndexRoute: typeof AppAgentsIndexRoute
  AppAudiencesIndexRoute: typeof AppAudiencesIndexRoute
  AppBillingIndexRoute: typeof AppBillingIndexRoute
  AppIntegrationsIndexRoute: typeof AppIntegrationsIndexRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
  AppSignalsIndexRoute: typeof AppSignalsIndexRoute
  AppTablesIndexRoute: typeof AppTablesIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppTablesTableIdRoute: AppTablesTableIdRoute,
  AppAgentsIndexRoute: AppAgentsIndexRoute,
  AppAudiencesIndexRoute: AppAudiencesIndexRoute,
  AppBillingIndexRoute: AppBillingIndexRoute,
  AppIntegrationsIndexRoute: AppIntegrationsIndexRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
  AppSignalsIndexRoute: AppSignalsIndexRoute,
  AppTablesIndexRoute: AppTablesIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
